# Generated by Django 3.2 on 2022-12-11 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('target_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('1', 'Assigned'), ('2', 'Failed.'), ('3', 'Completed.')], default='OPEN', max_length=5)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits_author', related_query_name='hit_author', to=settings.AUTH_USER_MODEL)),
                ('hitman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', related_query_name='hit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
