# Generated by Django 3.2 on 2022-12-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_hit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='status',
            field=models.CharField(choices=[('1', 'Assigned'), ('2', 'Failed.'), ('3', 'Completed.')], default='OPEN', max_length=5),
        ),
    ]
