# Generated by Django 3.2 on 2022-12-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_hit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='kind',
            field=models.CharField(choices=[('1', 'Boss'), ('2', 'Hitmen')], default='Hitmen', max_length=5),
        ),
    ]
